### PR TITLE
upgrade to react 17

### PR DESCRIPTION
**Pull request by mason-fish**
As noted in their [release notes](https://reactjs.org/blog/2020/08/10/react-v17-rc.html), there are no new features and very minimal breaking changes in this major release bump. The only thing I saw that we can change is removing the event persistence, which is no longer necessary. All manual and automated testing has passed locally.

signed-off-by: Mason Fish <mason@looky.cloud>

### CODE REVIEW

**Comment by jameskerr** [comment]
It looks like the failure is from our enzyme react adapter. Maybe this works? https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17

**Comment by mason-fish** [comment]
update: while my personal testing and integrations pass, the unit testing is blocked on the enzyme lib's react adapter update (https://github.com/enzymejs/enzyme/issues/2429#issuecomment-713251132).I'll close for now, and reopen when that changes.

**Comment by mason-fish** [comment]
@jameskerr I thought it would be better to wait for the official adapter since we aren't desperate to upgrade, wdyt?

**Comment by jameskerr** [comment]
Sounds good to me!

**Pull request closed without merging**
