### PR TITLE
Add Documentation for Adding Migrations

### PR DESCRIPTION
**Pull request by jameskerr**
@r-franke asked me on Slack how to generate some sample data to test a migration, so I figured I'd write some documentation about it and post it here for anyone in the future (myself included) to be reminded of how it's done.

### CODE REVIEW

**Comment by r-franke** [comment]
Great document. Looks solid.

**Comment by philrz** [comment]
@jameskerr: Please make sure to add links in `Home.md` and `_Sidebar.md` following the examples of what's already there. In fact, seeing your PR made me think of a minor wiki reorganization we should probably put in place before merging this PR. If you could review & approve https://github.com/brimsec/brim/pull/922, then you could rebase & follow that new approach, if you're cool with it.

**Comment by jameskerr** [comment]
Updated and rebased.

**Comment by jameskerr** [comment]
Updated and rebased.

**Comment by alfred-landrum** [comment]
writing looks good to me, let's allow @mason-fish the final review/approve.

**Pull request merged**
