### PR TITLE
Move from Flow to Typescript

### PR DESCRIPTION
**Pull request by jameskerr**
Flow is gone and TypeScript is here!

Babel still transpiles the code, but instead of typechecking with `npm run flow`, we'll now use `npm run tsc`.

TypeScript caught more errors that Flow did, so I've fixed those it found.

All files must now end in `.ts` and all JSX files must end in `.tsx`

### CODE REVIEW

**Comment by alfred-landrum** [comment]
@jameskerr : fyi, I pulled this onto my Windows dev machine, and hit the same issue as the CI, notice this line:
`Successfully compiled 0 files with Babel (222ms).`. For some reason, when I run `npm run build`, I don't see any files created under `dist`.

I also hit https://github.com/brimsec/brim/issues/1076 while trying to build locally on my windows machine, btw: if you try to repro this on your Windows VM, you'll need to run `choco install mingw` and edit package.json to use `mingw32-make.exe` instead of `make`.

**Comment by jameskerr** [comment]
@alfred-landrum thanks for doing the windows debugging. I'll see if I can get babel to make those files.

**Comment by mason-fish** [comment]
Awesome! I've been playing with this branch for a couple days now and everything seems solid to me. For such a large change I think we will have to lean on our tests a bit, but then again this is only changing the typing layer which has always been superimposed on the actual js code. So seems good to merge to me 👍

**Review by mason-fish — APPROVED** [review]

**Comment by alfred-landrum** [comment]
The windows changes work for me locally, and I verified that the git history for the files locally (not in github) reflects the edits:
`924 files changed, 6167 insertions(+), 35460 deletions(-)`
:shipit: from me

**Comment by jameskerr** [comment]
Fixes #1036

**Pull request merged**
